// Mocks generated by Mockito 5.4.6 from annotations
// in omdbapp/test/features/home/presentation/bloc/home_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:omdbapp/features/home/domain/entities/movie_entity.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$MovieEntityCopyWith_0<$Res> extends _i1.SmartFake
    implements _i2.$MovieEntityCopyWith<$Res> {
  _Fake$MovieEntityCopyWith_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieEntity extends _i1.Mock implements _i2.MovieEntity {
  @override
  bool get adult =>
      (super.noSuchMethod(
            Invocation.getter(#adult),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get originalLanguage =>
      (super.noSuchMethod(
            Invocation.getter(#originalLanguage),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#originalLanguage),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#originalLanguage),
            ),
          )
          as String);

  @override
  String get originalTitle =>
      (super.noSuchMethod(
            Invocation.getter(#originalTitle),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#originalTitle),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#originalTitle),
            ),
          )
          as String);

  @override
  String get overview =>
      (super.noSuchMethod(
            Invocation.getter(#overview),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#overview),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#overview),
            ),
          )
          as String);

  @override
  double get popularity =>
      (super.noSuchMethod(
            Invocation.getter(#popularity),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  String get releaseDate =>
      (super.noSuchMethod(
            Invocation.getter(#releaseDate),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#releaseDate),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#releaseDate),
            ),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  bool get video =>
      (super.noSuchMethod(
            Invocation.getter(#video),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get voteAverage =>
      (super.noSuchMethod(
            Invocation.getter(#voteAverage),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  int get voteCount =>
      (super.noSuchMethod(
            Invocation.getter(#voteCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.$MovieEntityCopyWith<_i2.MovieEntity> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$MovieEntityCopyWith_0<_i2.MovieEntity>(
              this,
              Invocation.getter(#copyWith),
            ),
            returnValueForMissingStub:
                _Fake$MovieEntityCopyWith_0<_i2.MovieEntity>(
                  this,
                  Invocation.getter(#copyWith),
                ),
          )
          as _i2.$MovieEntityCopyWith<_i2.MovieEntity>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
